export var MAPCOLONIES_TILES_URL = 'TILES_URL';
export var MAPCOLONIES_QUERY_URL = 'QUERY_URL';
export var MAPCOLONIES_GEOCODING_URL = 'GEOCODING_URL';
export var MAPCOLONIES_CATALOG_URL = 'CATALOG_URL';
export var TOKEN = 'TOKEN';
