global:
  cloudProvider: {}
  environment: {}
enabled: true
environment: production
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030
resetOnConfigChange: true
cloudProvider:
  imagePullSecretName: mapcolonies-pull-secret
  flavor: openshift

image:
  repository: localhost/mapcolonies/common/maps-playground
  tag: 0.0.1-4
  imagePullPolicy: IfNotPresent

s3:
  url: 'http://localhost:9000'
  bucket: 'temp'
  accessKeyId: 'user'
  secretAccessKey: 'password'

env:
  port: 8080
  targetPort: 8080

resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 150Mi

route:
  enabled: true
  https: true
  path: /
  host: playground
  wildcardPolicy: None
  port:
    targetPort: http
  tls:
    termination: edge
    certificate: ''
    key: ''
    caCertificate: ''
    insecureEdgeTerminationPolicy: Redirect # <- important
  timeout:
    enabled: false
    duration: 60s

ingress:
  enabled: false
  path: /
  host: localhost
  cors:
    enabled: true
    origin: '*'
